# Python Arrays

Array's are the foundation for all data science in Python. Arrays can be multidimensional, and all elements in an array need to be of the same type, all integers or all floats, for example.

### Advantages of using an Array

+ Arrays can handle very large datasets efficiently
+ Computationally-memory efficient
+ Faster calculations and analysis than lists
+ Diverse functionality (many functions in Python packages). With several Python packages that make trend modeling, statistics, and visualization easier.

### Basics of an Array

In Python, you can create new datatypes, called arrays using the NumPy package. NumPy arrays are optimized for numerical analyses and contain only a single data type.

You first import NumPy and then use the array() function to create an array. The array() function takes a list as an input.

In [1]:
import numpy as np

In [2]:
my_array = np.array([0, 1, 2, 3, 4])
print(my_array)

[0 1 2 3 4]


The type of my_array is a numpy.ndarray.

In [3]:
type(my_array)

numpy.ndarray

### Array Examples
#### Example of creating an Array
In the below example, you will convert a list to an array using the array() function from NumPy. You will create a list a_list comprising of integers. Then, using the array() function, convert it an array.

In [4]:
import numpy as np

a_list = [1, 2, 3, 4]
a_list

[1, 2, 3, 4]

In [5]:
an_array = np.array(a_list)
an_array

array([1, 2, 3, 4])

### Example of an Array operation
In the below example, you add two numpy arrays. The result is an element-wise sum of both the arrays.

In [6]:
import numpy as np

array_A = np.array([1, 2, 3])
array_B = np.array([4, 5, 6])

print(array_A + array_B)

[5 7 9]


### Example of Array indexing
You can select a specific index element of an array using indexing notation.

In [7]:
months_array = np.array(['Jan', 'Feb', 'March', 'Apr', 'May'])
print(months_array[3])

Apr


You can also slice a range of elements using the slicing notation specifying a range of indices.

In [8]:
print(months_array[2:5])

['March' 'Apr' 'May']


### Interactive Example of a List to an Array
In the below example, you will import numpy using the alias np. Create prices_array and earnings_array arrays from the lists prices and earnings, respectively. Finally, print both the arrays.

In [9]:
# IMPORT numpy as np
import numpy as np

# Lists
prices = [170.12, 93.29, 55.28, 145.30, 171.81, 59.50, 100.50]
earnings = [9.2, 5.31, 2.41, 5.91, 15.42, 2.51, 6.79]

# NumPy arrays
prices_array = np.array(prices)
earnings_array = np.array(earnings)

# Print the arrays
print(prices_array)
print(earnings_array)

[170.12  93.29  55.28 145.3  171.81  59.5  100.5 ]
[ 9.2   5.31  2.41  5.91 15.42  2.51  6.79]


# Introduction à NumPy
Nous allons travailler en interactif.

Vous pouvez utiliser l’éditeur Spyder de la distribution Anaconda.

La bibliothèque NumPy (http://www.numpy.org/) permet d’effectuer des calculs numériques avec Python. Elle introduit une gestion facilitée des tableaux de nombres.

Il faut au départ importer le package numpy avec l’instruction suivante :

In [10]:
import numpy as np

### Variables prédéfinies
#### Variable pi
NumPy définit par défaut la valeur de pi.

In [11]:
np.pi

3.141592653589793

### Tableaux - numpy.array()
#### Création
Les tableaux (en anglais, array) peuvent être créés avec numpy.array(). On utilise des crochets pour délimiter les listes d’éléments dans les tableaux.

In [12]:
a = np.array([[1, 2, 3], [4, 5, 6]])

#### Affichage

In [13]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
type(a)

numpy.ndarray

#### Accès aux éléments d’un tableau
Avertissement

Comme pour les listes, les indices des éléments commencent à zéro.

In [15]:
a[0,1]

2

In [16]:
a[1,2]

6

### La fonction numpy.arange()

In [18]:
m = np.arange(3, 15, 2)
m

array([ 3,  5,  7,  9, 11, 13])

In [19]:
type(m)

numpy.ndarray

In [21]:
n = range(3, 15, 2)
n

range(3, 15, 2)

In [22]:
type(n)

range

Noter la différence entre numpy.arange() et range() :

+ numpy.arange() retourne un objet de type numpy.ndarray.

+ range() retourne un objet de type range.

Ceci est également à distinguer d’une liste.

In [24]:
u = [3, 7, 10]
u

[3, 7, 10]

In [25]:
type(u)

list

Il est possible d’obtenir des listes en combinant list et range().

In [26]:
list(range(3, 15, 2))

[3, 5, 7, 9, 11, 13]

numpy.arange() accepte des arguments qui ne sont pas entiers.

In [27]:
np.arange(0, 11*np.pi, np.pi)

array([ 0.        ,  3.14159265,  6.28318531,  9.42477796, 12.56637061,
       15.70796327, 18.84955592, 21.99114858, 25.13274123, 28.27433388,
       31.41592654])

### La fonction numpy.linspace()

numpy.linspace() permet d’obtenir un tableau 1D allant d’une valeur de départ à une valeur de fin avec un nombre donné d’éléments.

In [28]:
np.linspace(3, 9, 10)

array([3.        , 3.66666667, 4.33333333, 5.        , 5.66666667,
       6.33333333, 7.        , 7.66666667, 8.33333333, 9.        ])

### Action d’une fonction mathématique sur un tableau
NumPy dispose d’un grand nombre de fonctions mathématiques qui peuvent être appliquées directement à un tableau. Dans ce cas, la fonction est appliquée à chacun des éléments du tableau.

In [29]:
x = np.linspace(-np.pi/2, np.pi/2, 3)
x

array([-1.57079633,  0.        ,  1.57079633])

In [31]:
y = np.sin(x)
y

array([-1.,  0.,  1.])